name: Generate Cypress Report

on:
  push:
    branches: [ main ]
  
jobs:

 cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - uses:  actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          run: |
            npm ci
            $(npm bin)/cypress verify
             
#       - name: Install a project with a clean slate
#         run: |
#           npm ci
#           $(npm bin)/cypress verify

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos and screenshots
        run: |
          mkdir -p public
          cp -r cypress/videos public/videos
          # cp -r cypress/screenshots public/screenshots

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
    
     
